### ISSUE TITLE
Left-Click Proceed NPC Menu Swaps

### ISSUE THREAD

**Issue by Expression77** [LlemonDuck/tombs-of-amascut#1]
-invocation presets with names
-swap talk to with 'proceed' after demi bosses
-swap talk to with 'begin' on npc before final boss

**Comment by LlemonDuck** [comment]
presets have now been added and released in v1.1.0

static swaps like that can be added manually with runelite custom swaps but i'll also add them to the plugin

**Comment by LlemonDuck** [comment]
added in 8147d919e6e9a7256f70de9610b0fb3362fff5ce
