### ISSUE TITLE
Warden P4 Screen Shake

### ISSUE THREAD

**Issue by osaapestosa** [LlemonDuck/tombs-of-amascut#100]
Is there anyway you would be able to create an option to turn off the warden P4 screen shaking - it triggers my epilepsy/photosensitivity and I love Toa :(

**Comment by LlemonDuck** [comment]
It will be a bit challenging to try and find the client script responsible for the screen shake, but if I can determine which one it is I am happy to add this feature. No promises on timeline or whether it will be possible at all, though.

**Comment by LlemonDuck** [comment]
After some more digging, I've learned that this isn't controlled by any client script which can be controlled by plugins, it's instead an engine feature. I've made a request to the RL maintainers to see if we can add a hook for it and will report back either way.

**Comment by osaapestosa** [comment]
You are awesome for digging into this I really really appreciate it !!! I’m not sure how these feature requests work but if it is possible and there’s anything I can do to compensate you for your time and effort would be happy to do so. Thanks again for checking into this (:

**Comment by LlemonDuck** [comment]
I was able to get an internal change made and merged into RuneLite in https://github.com/runelite/runelite/commit/5ade38ba2f7ba91f54117012516d419fac9265b9, which adds a global "disable camera shake" option to the Camera plugin, if that is preferable to you. Whenever the next RuneLite release is, I'll update the ToA plugin to have a Wardens-only disabler as well.

**Comment by osaapestosa** [comment]
That is so great thank you so much again for this I really really appreciate it - it’s going to be a huge life improvement for me to be able to safely enjoy/access content! Thank you very much again!!

**Comment by LlemonDuck** [comment]
Core RuneLite was finally updated last Wednesday, so I'll be releasing the feature in the next few hours.

**Comment by osaapestosa** [comment]
I just tried it out it is amazing thank you so so so much again!!!!!!
