### ISSUE TITLE
TOA chest audio

### ISSUE THREAD

**Issue by VeIzun** [LlemonDuck/tombs-of-amascut#102]
I cannot get my toa chest audio to play. I had no such issue on my previous computer and I am 100% positive I have the wav file saved correctly. My notification wav plays just fine. I am at the end of my rope.

**Comment by LlemonDuck** [comment]
The file _should_ be `.runelite/tombs-of-amascut/toa-chest.wav`. Can you check that's the case, and if not, post a screenshot of your .runelite/tombs-of-amascut folder?

**Comment by VeIzun** [comment]
I dont understand how can i check this. And why would that matter if i used the exact same audio file? I did the exact same process as it says to do and which worked originally.

**Comment by VeIzun** [comment]
https://i.imgur.com/IyWa1ld.png
