### ISSUE TITLE
SmellingSaltsCooldown feature sometimes does not allow you to eat smelling salts when you should be able to

### ISSUE THREAD

**Issue by haleyhaas** [LlemonDuck/tombs-of-amascut#105]
![image](https://github.com/user-attachments/assets/b46f7ca1-aa51-47a3-8a44-4ecd15d24466)

I've noticed over the last few days that while doing ToA, I will have ~1 minute or less on my smelling salt and will go to crush the salt to reapply the salt, but will not be able to because of the message "You are already boosted by smelling salts!"

It's inconsistent when it happens, but frequently I can't boost or boost.  In the provided image, we finished Kephri, claimed our smelling salts from the Supply Spirit, completed the Zebak puzzle and went to apply Smelling Salts for the first time of the raid in Zebak's room, and could not.

It seems like there's some sort of issue in determining how long ago the salt was last used and the 15 second delay before being allowed to eat salt again is occasionally blocking crushing both the first salt we try to use and reapplying salt when it's about to exprie.

**Comment by haleyhaas** [comment]
Updating, it seems to be caused by trying to salt while on cooldown from drinking another potion, or basically any action that would prevent you from eating the salt.  See video attached for demonstration.

Uploading 2024-10-17 23-14-51.mp4…

**Comment by LlemonDuck** [comment]
`isConsumed` isn't actually related to consuming an item, so that won't work, but I've made it more reliable by checking for the server's "salt boost timer" being set. (thanks jagex for sending c++ client values to the java client!)

Thanks for the report!
