### ISSUE TITLE
Info box for number puzzle ancient tablet

### ISSUE THREAD

**Issue by plxgue** [LlemonDuck/tombs-of-amascut#13]
An info box with the number seen on the ancient tablet after viewing it so you do not have to check your chat box.

**Comment by LlemonDuck** [comment]
May be able to add this at a later date when restrictions are relaxed, but it won't be on the roadmap for now.

**Comment by LlemonDuck** [comment]
added a full addition puzzle helper in 886c5783fe95ccee1247b5cd07b7745f935be498, will update this ticket again when released

**Comment by LlemonDuck** [comment]
released in 2.0.0
