### ISSUE TITLE
Preset name text overlapping UI after today's update

### ISSUE THREAD

**Issue by ThePharros** [LlemonDuck/tombs-of-amascut#17]
Today's update added the ornament kits to the loot panel, slightly shifting the icons vertically, making the previously placed text for preset names to now overlap:

![image](https://user-images.githubusercontent.com/18340303/189128464-7ea2eb98-72c8-4f77-a801-3fd653d037f2.png)

**Comment by LlemonDuck** [comment]
fixed in 321ffa758563200c23c5ac93b0644bf79f63e658
