### ISSUE TITLE
Light Puzzle Helper

### ISSUE THREAD

**Issue by jevonsp** [LlemonDuck/tombs-of-amascut#18]
Would be great to have a light puzzle helper, could even an interactive one appear in the side panel, or would that be disallowed?

With the other toa helper plugin it has a light puzzle helper, but i find it of little use since I cant input my room layout and trying to figure out how to get it to align with the presets and then solve them is more time than just solving it

**Comment by LlemonDuck** [comment]
added in 3595ef6af51468b91012dc13a80a132e8b026b9c will update this ticket again when released

**Comment by LlemonDuck** [comment]
released in 2.0.0
