### ISSUE TITLE
Path of Het overhead tick counter

### ISSUE THREAD

**Issue by Newbcake** [LlemonDuck/tombs-of-amascut#19]
Add an overhead tick timer that counts 9 ticks from entering the path of het room, this will help with clicking the seal on the correct tick.

This tick counter would be similar to the counters in other raid plugins like [tob qol ](https://github.com/damencs/tob-qol/issues), [cox additions](https://github.com/MoreBuchus/buchus-plugins/tree/a641dc2b925eb0757849730654d0aaf6c04a3145) and of course [visual metronome](https://github.com/vincent0955/Visual-metronome) but it would only appear in the path of het room.

I believe this would be within the rules, however an automatic tick counter that counts when the statue will actually fire its beam would not be. Manual calculation of when an npc attacks seems to be allowed.

**Comment by LlemonDuck** [comment]
I've been informed by Jagex that they plan to add an in-game visual cue for this mechanic, and to avoid adding one to the plugin.
