### ISSUE TITLE
Deposit-pickaxe Reminder

### ISSUE THREAD

**Issue by Yidz** [LlemonDuck/tombs-of-amascut#2]
Add a blinking arrow and some text over the statue/exit to deposit your pickaxe when the room is complete if you still have the pickaxe in your inv/equipped, like how tob qol reminds you to claim your loot from the chest by the bank after a tob run.

**Comment by LlemonDuck** [comment]
I like this but I may need to check with Jagex on whether it is okay first and will report back here once implemented/rejected.

**Comment by null-zero** [comment]
Another Idea for this would be to swap/remove the "enter" option on the door when you go to leave if a pickaxe is still equipped or in your inv

**Comment by LlemonDuck** [comment]
added in df5aae6ed2b7595edd4a44f0b9f287dcc4d7a9fb, and released in 2.0.0 today, check config to enable
