### ISSUE TITLE
Presets missing after jagex add theirs

### ISSUE THREAD

**Issue by oeg91** [LlemonDuck/tombs-of-amascut#20]
There is not presets plugin when you right click presets button after jagex add their presets. Tbh this plugin's is way better than jagex's

**Comment by LlemonDuck** [comment]
At the moment I am satisfied with Jagex's implementation of presets, but I am willing to bring back the plugin-based presets once I take the time to have it also remove the Jagex preset panel.

This is fairly low-priority for now, however.

**Comment by LlemonDuck** [comment]
Added in bb17f94ad9ac2162e6a065deaf9c5a812d1570f2, released in 2.0.0
