### ISSUE TITLE
Show path of Het solutions

### ISSUE THREAD

**Issue by 8992scripts** [LlemonDuck/tombs-of-amascut#24]
It would be useful if it highlighted the tiles where mirrors need to be placed to solve the puzzle

**Comment by rugg0064** [comment]
I wrote a solver for path of het last night as a standalone plugin. Is there still any interest in me integrating this into the plugin?

**Comment by 8992scripts** [comment]
I am still interested

**Comment by LlemonDuck** [comment]
I've pushed a solver in 113a296c44aac40ca5fa4d43071e8f840481c6d8

Will test a bit more tomorrow then release

![image](https://github.com/LlemonDuck/tombs-of-amascut/assets/1868974/a0f17cbc-bd3e-4545-8903-57d356f363d6)

**Comment by LlemonDuck** [comment]
Released
