### ISSUE TITLE
Ahhka memory puzzle indicator/solver

### ISSUE THREAD

**Issue by timrwwatson** [LlemonDuck/tombs-of-amascut#26]
Much like the memory puzzle for path of scabaras, where the plugin shows which order to stand on the squares. 

Could the plugin show which of fire/air/water/earth to stand in -> put numbers on each quadrant etc

**Comment by LlemonDuck** [comment]
Not allowed within the third party client guidelines. This is different than Scabaras since Akkha is a boss.
