### ISSUE TITLE
Insanity Trainer

### ISSUE THREAD

**Issue by A-RooK** [LlemonDuck/tombs-of-amascut#32]
I would like to see an addition to this plugin - the plugin tells you if you complete the skulls section during P2 Warden within the time allotted based on your scale.

Think of this as a way to train for "insanity" without having it enabled and risking a death.  Maybe it could be as simple as having a countdown timer over the skulls heads or a timer in an info box that starts counting down when skulls appear and gives you a "failed" if you don't clear them in time.

**Comment by LlemonDuck** [comment]
Probably better suited as an external plugin as it wouldn't have a use in most users' raids. You can already practice insanity on a low-invocation solo run with only it enabled: the mechanics are the same regardless of raid level.
