### ISSUE TITLE
Feature Request - Per Room Reminder of invokes that are enabled

### ISSUE THREAD

**Issue by nkacena** [LlemonDuck/tombs-of-amascut#33]
I often find myself in we do raids TOA raids and mid way through wondering if gap is on/etc Before each boss could you have either of the following;

- quick flash on UI of active invokes
- sidebar list of invokes like how the baba puzzle shows the waves

Thanks!

**Comment by nkacena** [comment]
just found out this was previously requested and turned down based on how jagex stores invokes. RIP

**Comment by LlemonDuck** [comment]
Yes, unfortunately we don't enough information on the client side, initial request was #21 for anyone who comes across this later
