### ISSUE TITLE
Add points tracker

### ISSUE THREAD

**Issue by thejdubs** [LlemonDuck/tombs-of-amascut#34]
Now with the official points calculations and drop rates revealed it should be possible to track it throughout the raid.
Track damage in each room for team and self, seems like simple multipliers based on damage.
Can track % contribution and % drop chance throughout as well.
"tob damage counter" plugin could be a good jumping off point

**Comment by LlemonDuck** [comment]
added in 10167029b687ce3306a5cac12341977fd737e82f, not yet released to public

**Comment by LlemonDuck** [comment]
released to plugin hub

**Comment by thejdubs** [comment]
awesome, youre on the ball. didnt notice the branch
