### ISSUE TITLE
Points Tracker: Warden P1->P2 Transition Points Inaccuracy

### ISSUE THREAD

**Issue by Mad-as-heck** [LlemonDuck/tombs-of-amascut#35]
Extra points are given on the counter at wardens.
-At the end of p1, there's an extra ~2000 points given for the hitsplat on the warden which isn't chosen for p2. 
-The core on p2 gives points when the multiplier should be 0

MVP points also seem weird (potentially missing for puzzles?), but I'm not 100% certain how it should work.

**Comment by LlemonDuck** [comment]
I've fixed a few issues now (including the p2 core points) in v2.2.0, which just released to the plugin hub.

Puzzle points are awarded upon leaving the room, and are just estimates from the wiki.

>  -At the end of p1, there's an extra ~2000 points given for the hitsplat on the warden which isn't chosen for p2

This one I was not aware of and will still need to fix

**Comment by Mad-as-heck** [comment]
> Puzzle points are awarded upon leaving the room, and are just estimates from the wiki.

You get points from the puzzles themselves which match the wiki numbers, but I don't see the MVP points from the puzzles, only the 5x MVP points from each boss. The wiki people think it's 300 per puzzle as well, how that's determined.... no idea...
![image](https://user-images.githubusercontent.com/54958885/200420671-d6570190-694c-4a3c-a7a6-70186d392c66.png)

**Comment by LlemonDuck** [comment]
I'm adding 300 points per room to account for MVP in 1e46813a1fc0cc01df319e10d93baedc64a733ac and accounting for the p1->p2 transition hitsplat in 63357ee54e5cfe547630e7398b9a7ef8c64076b7
