### ISSUE TITLE
unique % seems to be off

### ISSUE THREAD

**Issue by thejdubs** [LlemonDuck/tombs-of-amascut#36]
got 14699 points at 150i should be like 1.95% but shows 1.4%

**Comment by thejdubs** [comment]
calculation code looks good, maybe it isn't updating correctly at the end?

**Comment by LucasChilders** [comment]
+1 to this. Was in a duo with a friend, I had more points but he had a higher unique chance.

**Comment by derekmu** [comment]
I'm confused about this feature as well.

I ran a solo 290 earlier that said I had over 6% chance. I didn't take a screenshot.

I just ran a 300 that says I only have a 1.8% chance with 19281 points?

![image](https://user-images.githubusercontent.com/6192907/200447727-406f82c8-4245-47f5-94ae-e4bae7b1617f.png)

The wiki calculator says:

> With no deaths, this raid will give approximately 19,114 contribution points. With a raid level of 300, this equates to a 4.2476% chance of receiving a purple drop, and a 0.1365% chance of receiving the pet. 

So the contribution points seem right but the drop chance seems wrong?

**Comment by derekmu** [comment]
Did another run right after and with almost the same points it says 4.2% chance.

![image](https://user-images.githubusercontent.com/6192907/200452646-c9bb4895-4a6d-49c5-acf0-a69211ef8b0f.png)

It's right some of the time. Maybe the raid level that it reads isn't always right?

**Comment by derekmu** [comment]
That's what occurred to me on a code scan. I'm not set up to test, though. I couldn't see a way to manually reset it either.

I guess if I see it in another raid I'll disable/reenable the plugin to see if that fixes it.

**Comment by LlemonDuck** [comment]
Thanks all for your interest. I'm fairly certain the issue lies in raid level detection. I have a fix that I will roll out tomorrow, as well as some more NPC point tracking fixes.
