### ISSUE TITLE
Target time in timer not being displayed

### ISSUE THREAD

**Issue by bxnev** [LlemonDuck/tombs-of-amascut#37]
![image](https://user-images.githubusercontent.com/117731558/200552806-58a9ab4f-b2be-4b86-b6c0-0c10574da1b2.png)

Target time in timer checked, in raid doesn't show timer.

![image](https://user-images.githubusercontent.com/117731558/200553657-84f75f58-e3b9-4d59-87d6-3513967a90a0.png)

**Comment by bxnev** [comment]
I see it works for some others not sure if this is something I can fix myself

**Comment by LlemonDuck** [comment]
It pulls the target time from the chat when entering ToA, or when the plugin is enabled. Can you send a screenshot of your chat with the message saying `Overall time to beat: ...`?

Also, are there any errors in your client.log? If you're not sure, you can upload the entire file here. (C:\Users\...\.runelite\logs\client.log on Windows, Home/.runelite/logs/client.log on macOS).

**Comment by bxnev** [comment]
![image](https://user-images.githubusercontent.com/117731558/200633140-8a788420-b6cf-4fd8-ac10-62e05df1b2c4.png)



[client.log](https://github.com/LlemonDuck/tombs-of-amascut/files/9963681/client.log)

**Comment by LlemonDuck** [comment]
I see... The issue lies in how I am detecting timestamps, and it is only compatible with "Precise timing" enabled. I will add support for non-precise timing, but for now you can resolve this by enabling precise timing in your OSRS settings:

![image](https://user-images.githubusercontent.com/1868974/200635028-9805a8f5-597e-46f3-acc4-6f0555c33576.png)

**Comment by LlemonDuck** [comment]
Fixed in 4405f7b98dd3f636aada7228a2e32626615e39a1, but not released to plugin hub yet. I'll update this ticket again when released.

**Comment by LlemonDuck** [comment]
released
