### ISSUE TITLE
Show which prayer icon to select when Stay Vigilant (Akkha) is active

### ISSUE THREAD

**Issue by KyleGlarum** [LlemonDuck/tombs-of-amascut#40]
I am learning stay vigilant it would be nice to know which prayer to select (by showing a prayer icon in the corner during the akkha fight) and maybe a highlighted melee style icon to show which melee setup i should attack with (so if he is in his ranging phase which is where you attack with melee - above him he will have mage and range prayers activated - maybe show a (for example) blue highlighted strength skill icon indicating to attack him with melee, and a (for example) red ranging icon to show to pray with protection from missiles

**Comment by LlemonDuck** [comment]
This is expressly forbidden by Jagex's [Third Party Client Guidelines](https://secure.runescape.com/m=news/third-party-client-guidelines?oldschool=1):

> Indicates which prayer to use in any combat situation
