### ISSUE TITLE
Insanity Side Indicator

### ISSUE THREAD

**Issue by izaakgray** [LlemonDuck/tombs-of-amascut#41]
Probably out of the scope of whats allowed on runelite but would be very nice to have an indicator for which side you were last on during warden with insanity on

**Comment by LlemonDuck** [comment]
This would run afoul of Jagex's [Third Party Client Guidelines](https://secure.runescape.com/m=news/third-party-client-guidelines?oldschool=1) in a couple ways:

> Adds additional visual or audio indicators of a boss mechanic except in cases where this is a manually triggered external helper.

> Automatically informs you where or where not to stand in a boss fight. This applies to only automatic indicators, and not tiles which have been manually marked.
