### ISSUE TITLE
Suggestion: Party Ba-Ba Puzzle

### ISSUE THREAD

**Issue by InfernoStats** [LlemonDuck/tombs-of-amascut#43]
If a user is in a RuneLite party, they'd get a `ModelOutlineRenderer` indicating the status of the current issue (red for not resolved and green for resolved). The outlined objects would be the vents, pillars, and players for corruption. Players that are not in the party performing actions would only resolve issues for players in the party if the party member had their corruption cured - vents and pillar animations can be hidden. The implementation would rely on game chat messages to deduce the current state.

For example:
```Java
public static final Pattern PILLAR_PROBLEM_PATTERN =
  Pattern.compile("<col=[A-Fa-f\\d]+>You sense an issue with the roof supports\\.");
public static final Pattern PILLAR_RESOLVE_PATTERN =
  Pattern.compile("<col=[A-Fa-f\\d]+>You repair the damaged roof support\\.");
public static final Pattern PILLAR_SUCCESS_PATTERN =
  Pattern.compile("<col=[A-Fa-f\\d]+>Apmeken\'s Sight guides (?:you|your group) into repairing the roof supports\\.");
public static final Pattern PILLAR_FAILURE_PATTERN =
  Pattern.compile("<col=[A-Fa-f\\d]+>Damaged roof supports cause some debris to fall on you!");
```

I'd PR this if you would accept it.

**Comment by LlemonDuck** [comment]
I'm inclined to believe this will not be allowed, but I've passed on the question to Jagex before adding/rejecting outright.

**Comment by LlemonDuck** [comment]
Jagex is not interested in this feature being part of the plugin.

**Comment by YvesW** [comment]
Would this feature be allowed by Jagex in case the party integration is completely scrapped, i.e. highlighting issues after people have called them out in chat? This would still force the person with the sight to actively communicate the issue in chat, in contrary to an implementation with party integration.

**Comment by LlemonDuck** [comment]
I'm sure that would be fine

**Comment by YvesW** [comment]
I've asked InfernoStats/Nick Ints and they are not interested in making this. Is it okay if I make this into a separate plugin to allow for some more customization options and since my coding capabilities would very likely not live up to your standard?
