### ISSUE TITLE
Inaccurate Points Milking Kephri with Soldier Beetle

### ISSUE THREAD

**Issue by RonnyTommy548** [LlemonDuck/tombs-of-amascut#44]
If you leave the soldier alive, it will heal kephri and allow you to deal a lot more damage to the boss. The point tracker will increment points, but the white loot at the end of the raid does not reflect this increase in points. I tested this in a 400 raid lvl and got like 24.5k points, but I went back and checked the loot and it was off by about 2k points, which is how many points I gained over my normal runs (around 22k). My conclusion is that there is a certain damage cap on kephri that does not reward points once you exceed it.

**Comment by LlemonDuck** [comment]
I've passed this on to the wiki team and we will try to do further testing to determine what the limit is, then I will implement it into the plugin. I assume not many people are attempting to draw out Kephri as long as possible just for points boosting, so I'm not concerned about leaving the behaviour in as it currently is until we can land on the correct solution.

**Comment by LlemonDuck** [comment]
This is an old issue but there is a points cap of 20k per room, which is implemented correctly currently.
