### ISSUE TITLE
Path of Scabaras sequence numbers still appear when alpha is 0

### ISSUE THREAD

**Issue by adkscherch** [LlemonDuck/tombs-of-amascut#48]
I'd like to use Path of Scabaras's overlay for the light and number puzzles alone as I prefer doing the other puzzles myself, but if the overlay is on the sequence numbers still appear (just in black) regardless of what I set their alpha to (I think the obelisk puzzle has the same issue, but I never do that one so I'm not sure). If I turn on the side panel instead of the overlay, the light puzzle doesn't get its highlighted tiles either, so that's unfortunately not a perfect solution. 

Essentially I'd like to see either an option to disable the puzzle helpers individually, or have the numbers for the sequence helper properly vanish instead of simply appearing as black numbers.

**Comment by LlemonDuck** [comment]
fixed in eb1ef5107af6cc98b77780de04889bb73e94e505
