### ISSUE TITLE
recolor sarcophagus based on loot

### ISSUE THREAD

**Issue by rdutta** [LlemonDuck/tombs-of-amascut#50]
This is something I was messing around with and I'm wondering if this would be a desirable feature or if it would be too much. It hides the loot roll animation and changes the color based on what item is rolled.

https://user-images.githubusercontent.com/38548565/216852278-02be354f-dbfa-4dc3-a562-691c1452b85e.mp4

![config](https://user-images.githubusercontent.com/38548565/216754789-43466ffa-b37a-4534-9b30-038dfdd2790c.png)

**Comment by LlemonDuck** [comment]
Neat! I like it. Would you like to PR it?

It would add even more options to the config, but I think that's fine as long as it is off by default.
