### ISSUE TITLE
Highlight Kephri Dung strike swarm indicator

### ISSUE THREAD

**Issue by DiscoDiscoPartyParty** [LlemonDuck/tombs-of-amascut#51]
just before Kephri does a dung strike a scarab swarm surrond the targets, if this could be outlined with a custom colour it would really help

**Comment by LlemonDuck** [comment]
This would be disallowed by the [Third Party Client Guidelines](https://secure.runescape.com/m=news/third-party-client-guidelines?oldschool=1).

> Indicates the time where a boss mechanic may start or end

and
> Adds additional visual or audio indicators of a boss mechanic except in cases where this is a manually triggered external helper.
