### ISSUE TITLE
Points Tracker Issue

### ISSUE THREAD

**Issue by Poclam** [LlemonDuck/tombs-of-amascut#52]
The wiki for toa reward points says "Players start the raid with 5,000 total reward points." The plugin, however, displays 0 points upon entering the raid? Just wondering why those 5000 points are not displayed on the points tracker as it accounts for a big difference in unique chance.

**Comment by LlemonDuck** [comment]
This was not well communicated from the dev team, but those 5000 points are deducted from your total at the end of the raid. They are there to make early deaths meaningful, and don't actually contribute to your chance of earning a drop.

The plugin does account for this, and is the reason you can go negative in points with the plugin (you can "bottom out" the plugin point tracker at -5000). They are just hidden for simplicity.
