### ISSUE TITLE
Suggest & highlight optimal solves for Zebak's "Great Roar" special attack

### ISSUE THREAD

**Issue by hotpheex** [LlemonDuck/tombs-of-amascut#54]
Hey there absolutely love the plugin. Just a shower thought that I had, I wonder if it would be possible to suggest/highlight water jar solves for Zebak's Great Roar (hide behind the rocks) special attack, similar to how the plugin solves the Scabaras puzzles. I haven't played with runelite plugins before but if you think it's a feature worth adding and would be feasible I'm happy to work on a PR for it.

**Comment by LlemonDuck** [comment]
This would be against the [Third Party Client Guidelines](https://secure.runescape.com/m=news/third-party-client-guidelines?oldschool=1).
