### ISSUE TITLE
Point tracker increases player points everytime mvp item is spawned/dropped to the ground

### ISSUE THREAD

**Issue by Roskis** [LlemonDuck/tombs-of-amascut#56]
Being rewarded with boss MVP points should happen only once per raid per boss, but picking up and dropping the same MVP item multiple times will result to an incorrect amount of points.

Easy repro in game: Defeat any boss, pick up the MVP item, drop the MVP item, and repeat last two steps.

**Comment by LlemonDuck** [comment]
fixed in eeded2330221108901f95613cb66b9f05898692c
