### ISSUE TITLE
Highlight entrance to skip scabaras obelisks

### ISSUE THREAD

**Issue by rdutta** [LlemonDuck/tombs-of-amascut#57]
![java_ZYomsl0lpE](https://user-images.githubusercontent.com/38548565/226221394-b2fa75ec-3b8b-4828-b37d-336aeae774b4.png)
edit: It doesn't seem to be possible to recolor the red flames because the model(?) is shared by both entrances.

**Comment by LlemonDuck** [comment]
added in 5368464bba8752f2d7670f65a124dfe60e3b3d3a
