### ISSUE TITLE
Add other pickaxes to left click deposit

### ISSUE THREAD

**Issue by TerrorNisse** [LlemonDuck/tombs-of-amascut#59]
Would be nice for ironmen to have other options of pickaxes to be added. The one I had specifically in mind is "Gilded pickaxe".

Thank you

**Comment by LlemonDuck** [comment]
It's my intention to have all pickaxes added, so I've just added the Gilded pickaxe in 4f2a46ed6d1e4f07bbb19406e0fdc7251d31b583. Let me know if you find any others that are not included.
