### ISSUE TITLE
Screenshot Invocations Not Working

### ISSUE THREAD

**Issue by Jack-Bruce-Dev** [LlemonDuck/tombs-of-amascut#60]
Unable to copy invocation screenshot from clipboard

**Comment by Jack-Bruce-Dev** [comment]
![image](https://user-images.githubusercontent.com/92029623/232458466-b7f75ec0-71ff-4564-ac33-3bf221c0f7d5.png)

**Comment by Jack-Bruce-Dev** [comment]
Above screenshot added is the result of taking invo screenshot

OS: Mac

**Comment by LlemonDuck** [comment]
Your image is not viewable, but I will take a look.

**Comment by Jack-Bruce-Dev** [comment]
Yeah exactly that.
Image not viewable but that was what was pasted from clipboard.
Thanks


Sent from Yahoo Mail for iPhone


On Tuesday, April 25, 2023, 8:38 pm, LlemonDuck ***@***.***> wrote:




Your image is not viewable, but I will take a look.

**Comment by LlemonDuck** [comment]
I cannot replicate the issue. Perhaps it is macOS-specific?

Does anything appear in your client logs? Finder -> Cmd+Shift+G -> `~/.runelite/logs/client.log`

<details>
  <summary>**Screenshots**</summary>

![image](https://user-images.githubusercontent.com/1868974/234404410-c705651f-f185-43a0-be11-19a64b601638.png)

![image](https://user-images.githubusercontent.com/1868974/234404520-e278c50f-3439-4c1c-9fa9-1206950ecd5d.png)

</details>

**Comment by Jack-Bruce-Dev** [comment]
Hi Llemon,
Please find attached the logs before and after screenshots.
I took 2 screenshots as part of this test.
Cheers.
Kind regards,Jack Bruce
Integration SME, Shell
***@***.***: +447397203302
 

    On Tuesday, 25 April 2023 at 22:11:45 BST, LlemonDuck ***@***.***> wrote:  
 
 


I cannot replicate the issue. Perhaps it is macOS-specific?

Does anything appear in your client logs? Finder -> Cmd+Shift+G -> ~/.runelite/logs/client.log
 **Screenshots**

**Comment by LlemonDuck** [comment]
If you're attaching things via email, I can't see them. You'll have to come to the website to upload them.

**Comment by Jack-Bruce-Dev** [comment]
[client_pre-screenshot.log](https://github.com/LlemonDuck/tombs-of-amascut/files/11330244/client_pre-screenshot.log)
[client_post-screenshot.log](https://github.com/LlemonDuck/tombs-of-amascut/files/11330245/client_post-screenshot.log)

Apologies, here you go.

**Comment by LlemonDuck** [comment]
There's nothing in the logs about it, and I don't have a mac device to test this on my own. Will have to wait until someone is able to debug under the same setup.

**Comment by kuhnertdm** [comment]
I'm not able to see any of these screenshots either, but if it's the issue with the screenshot being "cut off", I believe that only happens when the reward info panel is disabled. If you click the "rewards" button at the bottom of the invocations menu, then take a new screenshot, it should have all the right proportions.

**Comment by Jack-Bruce-Dev** [comment]
Hi,
Furthmore, the invocations screenshot seems to be working... however it does not work when trying to paste via the clipboard, so that seems to be the issue.
See attached.
Thanks.

Kind regards,Jack Bruce
Integration SME, Shell
***@***.***: +447397203302
 

    On Monday, 19 June 2023 at 09:26:28 BST, Jack Bruce ***@***.***> wrote:  
 
 Hello,
This does not work.
Even having the rewards screen open/close or any version of tests do not work.
Attached is a screenshot of me testing sending to a friend and another screenshot of a normal RL screenshot working correctly.

Thanks.

Kind regards,Jack Bruce
Integration SME, Shell
***@***.***: +447397203302
 

    On Saturday, 17 June 2023 at 15:23:26 BST, Derek Kuhnert ***@***.***> wrote:  
 
 


I'm not able to see any of these screenshots either, but if it's the issue with the screenshot being "cut off", I believe that only happens when the reward info panel is disabled. If you click the "rewards" button at the bottom of the invocations menu, then take a new screenshot, it should have all the right proportions.

**Comment by LlemonDuck** [comment]
Attachments are not carried over from email to GitHub you'll have to come to the website to attach something

**Comment by Jack-Bruce-Dev** [comment]
Closing issue as invo is being screenshotted and saved in RL files but not possible to Cmd+V to paste it.
