### ISSUE TITLE
Plugin drop down menus auto-expanding

### ISSUE THREAD

**Issue by Nikskill** [LlemonDuck/tombs-of-amascut#62]
Unlike other plugins, the drop down menus in the plugin settings do not remember which state they were in (collapsed or expanded).

For example, with all drop downs collapsed like this:
![image](https://github.com/LlemonDuck/tombs-of-amascut/assets/60371751/c02d36d2-e3c8-4897-8754-ebfdf24e8cdf)
After a client reset it will revert to this:
![image](https://github.com/LlemonDuck/tombs-of-amascut/assets/60371751/f6b22ace-99a9-42b8-b743-a591b895606f)

**Comment by LlemonDuck** [comment]
I'm not seeing that other plugins remember this state, nor is there any functionality in the RuneLite ConfigPanel to try and support this:

https://github.com/runelite/runelite/blob/master/runelite-client/src/main/java/net/runelite/client/plugins/config/ConfigPanel.java#L247-L256

(If you're not a programmer, just note there's nothing in there using `ConfigManager`)

I'm going to close this for now, but let me know if you have an example of a plugin that for sure remembers this state.
