### ISSUE TITLE
Suggestion : Timer Wheel On 1 Or More Red Skulls

### ISSUE THREAD

**Issue by brodybud** [LlemonDuck/tombs-of-amascut#64]
Is it possible you fine folks could add a timer wheel similar to the one in the akkha puzzle room to a red skull during the warden fight. So that the timer turns green when the skulls are going to explode. PLEASE <3 Would be a tad easier to dodge boulders and know when to skull skip without spam clicking a skull. 

![image](https://github.com/LlemonDuck/tombs-of-amascut/assets/138569442/7cc325be-af74-42bd-b1da-1727f8e3a5fd)

**Comment by LlemonDuck** [comment]
This would violate Jagex' [Third Party Client Guidelines](https://secure.runescape.com/m=news/third-party-client-guidelines?oldschool=1):
> Indicates the time where a boss mechanic may start or end
