### ISSUE TITLE
Points overlay flashes on login

### ISSUE THREAD

**Issue by kentor** [LlemonDuck/tombs-of-amascut#65]
I'm seeing the "ToA Points" overlay flash when I login for the first time on fresh launch of runelite, when I'm outside of ToA.

For example, I'm in the GE and I see the overlay for a split second. This is a frame of a recording:

![image](https://github.com/LlemonDuck/tombs-of-amascut/assets/240493/4b10cf95-214a-43e0-bca0-764f8f77e1bd)

**Comment by LlemonDuck** [comment]
I was very confused by this bug for a long time but your pointing out of it only happening on a fresh launch solved it for me! Fixed in 1d834a81e0202b338dc3257332c7ca7c73f3b25b

**Comment by kentor** [comment]
thanks for the fix! 🫡
