### ISSUE TITLE
Plugin causes crashing and freezing in path of scarabas puzzle

### ISSUE THREAD

**Issue by h0dgep0dge** [LlemonDuck/tombs-of-amascut#66]
Unfortunately I wasn't able to collect debug information, but we spent a long time troubleshooting and the issue was consistently reproduced with the plugin on (even on a completely fresh install), and never occurred with the plugin off. If you have some specific steps to take to collect more information, let me know and i'll see what i can do.

**Comment by LlemonDuck** [comment]
If you have client logs from the time of the crash that would be best. `C:\Users\<you>\.runelite\logs\client.log` on Windows or `~/.runelite/logs/client.log` on macOS/Linux.

When you have a crash, immediately upload that file here and I'll take a look. If you restart your client first it could overwrite the log file.
