### ISSUE TITLE
Pickaxe cavity in lobby highlight/notification

### ISSUE THREAD

**Issue by Torrent-Rage** [LlemonDuck/tombs-of-amascut#67]
Option to add a reminder (on screen notification?) if the pickaxe deposit cavity in the lobby is empty if you were to remove your pickaxe and use it elsewhere, but didn't put it back when you've returned to the lobby.

**Comment by LlemonDuck** [comment]
a1370728844cf9097cdfbd88d10bace744d973eb adds the left-click deposit/take swap

4a418636845c30257c9545d989605f5697b830ca adds the option to prevent entry into the raid if you do not have a pickaxe stored

bb2c37a515c375c91d94ab4c7692d04ebec2e2f6 adds a visual overlay option to both lobby and puzzle room

https://github.com/LlemonDuck/tombs-of-amascut/assets/1868974/9771de38-d0c5-43be-99e1-ce39b25d172d
