### ISSUE TITLE
Kephri final puzzle infer last tile

### ISSUE THREAD

**Issue by stevenwaterman** [LlemonDuck/tombs-of-amascut#69]
Of the 9 tiles on each side at the end of the kephri puzzle, the plugin could infer the 9th symbol after revealing only 8 of them, since it's always the same 9 symbols.

I'm currently doing this mentally by only revealing 8 of the tiles and then figuring out what the last one must be, but the plugin doing it automatically and marking it with a label would make things easier.

I could attempt to implement this myself and submit a PR if you agree it would be helpful and allowed (though it'd probably be much better code if someone else did it)

**Comment by LlemonDuck** [comment]
That puzzle solver in particular is already a compromise from Jagex due to former cheat plugins revealing all the tiles without having to flip over at all.

I prefer not to alter the behaviour at this point.
