### ISSUE TITLE
Smelling Salt Expiry Notifications

### ISSUE THREAD

**Issue by LlemonDuck** [LlemonDuck/tombs-of-amascut#7]
Notify the player when their salts expire.

Pending RL core work on adding salts to the timer plugin to base this off of.

**Comment by LlemonDuck** [comment]
The game already has messages for all three of these buffs, so I'm not sure how this should even provide more useful notifications. This was originally a request from a Reddit user.

**Comment by ThePharros** [comment]
If it helps, there's two vanilla chatmessages that could make this more trivial than to be timer dependent:

> Your smelling salts effect has almost ran out!

> The boost from the smelling salts has worn off!

**Comment by Reeenatu** [comment]
How about a timer that shows when the salt is gonna "reboost up"?, iirc it happens every 15 seconds. Could be useful so we know if its "safe" to brew up.

**Comment by LlemonDuck** [comment]
> How about a timer that shows when the salt is gonna "reboost up"?, iirc it happens every 15 seconds. Could be useful so we know if its "safe" to brew up.

fwiw, [Better Overload](https://runelite.net/plugin-hub/show/betteroverload) has this feature.

**Comment by LlemonDuck** [comment]
Closing as there's not really anything to add for me that wouldn't conflict with Better Overload, linked above.
