### ISSUE TITLE
Question: Sources for Room Point Caps

### ISSUE THREAD

**Issue by jb1361** [LlemonDuck/tombs-of-amascut#74]
I have been trying to find sources for the room point cap to answer these two questions.

1: Is the point cap per room actually 20,000?
2: Is the point cap per room raid wide or individual wide?

**Comment by LlemonDuck** [comment]
Almost everything implemented came directly from this blog post: https://secure.runescape.com/m=news/a=97/tombs-of-amascut-drop-mechanics--osmumtens-fang?oldschool=1

Specifically toward your questions:
> You cannot gain more than 20,000 Room points as an individual in a single room.

**Comment by LlemonDuck** [comment]
If there's anything else you're curious in I may have another source / more info, feel free to ask other things!

**Comment by jb1361** [comment]
Thanks, that quote from the wiki is specifically what I'm trying to find a source for.
