### ISSUE TITLE
Path of Het incorrect mirror solve

### ISSUE THREAD

**Issue by leguaan** [LlemonDuck/tombs-of-amascut#75]
![image](https://github.com/LlemonDuck/tombs-of-amascut/assets/22646423/73648fc2-7d3b-4009-ad3d-872d37bdae07)
There's no 4th mirror, correct solution is to use 3 to go through north past the static mirrors.

**Comment by LlemonDuck** [comment]
I can't replicate this, but let me know if you run into it again.
