### ISSUE TITLE
Path of Apmeken call reminder 

### ISSUE THREAD

**Issue by SimenSteinsland** [LlemonDuck/tombs-of-amascut#76]
I usually play with chat closed which usually makes me miss the DD call at Path of Apmeken.
I'd love a simple 2D graphic to remind to call when the chat message "You sense an issue in the room" is sent. Similar to the graphic that Thrall Helper uses.
![68747470733a2f2f692e696d6775722e636f6d2f496d61394467502e706e67](https://github.com/LlemonDuck/tombs-of-amascut/assets/31660773/e7c7e096-3757-41b1-a76d-2e82a11b46fc)

**Comment by LlemonDuck** [comment]
There is already a sound cue, visual cue, and chat cue so I'm not interested in adding more. There are other plugins that can help with this such as chat notifications, though.
