### ISSUE TITLE
TOA Plugin Incompatible

### ISSUE THREAD

**Issue by burn-ham** [LlemonDuck/tombs-of-amascut#78]
Runelite is stating that the plugin is incompatible and requires an update:

![image](https://github.com/LlemonDuck/tombs-of-amascut/assets/143135333/020aa69b-7818-4c87-a079-9aac8d0499c1)

**Comment by Felanbird** [comment]
It's broken due to an accidental change on RuneLite's end, it'll be fixed probably later today
![image](https://github.com/LlemonDuck/tombs-of-amascut/assets/41973452/0d224f11-6aa0-46e1-b9fb-77e8e5e5dcaa)

**Comment by itsskyguy** [comment]
> It's broken due to an accidental change on RuneLite's end, it'll be fixed probably later today ![image](https://private-user-images.githubusercontent.com/41973452/333212312-0d224f11-6aa0-46e1-b9fb-77e8e5e5dcaa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0ODM1MDcsIm5iZiI6MTcxNjQ4MzIwNywicGF0aCI6Ii80MTk3MzQ1Mi8zMzMyMTIzMTItMGQyMjRmMTEtNmFhMC00NmUxLWI5ZmItNzdlOGU1ZTVkY2FhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDE2NTMyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmNjc1MGIxZmFiNjYwM2Y4NDNkOWFkNTNmYTg0ZDhhMWVmOTViNjMyOGQ4MWIxZWU4ZmUwMmFjNjkxOGYwZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._TxY-RA7K9mH3-kJpf0vRNCTU2M6F9fWoBqYUxknN0k)

Where did you find this info?
