### ISSUE TITLE
Cannot delete preset

### ISSUE THREAD

**Issue by TimOosterom** [LlemonDuck/tombs-of-amascut#8]
There is no way to delete a preset. Setting it to no invocations and saving over that just sets it to level 0.

**Comment by LlemonDuck** [comment]
Use Shift+Right-click on the Presets button.

**Comment by LlemonDuck** [comment]
This should be in the README actually so I'll reopen until I can add it there.

**Comment by LlemonDuck** [comment]
Added in 939c3adac4fbf46f6f9f8f297a47ced9937b3cfb
