### ISSUE TITLE
Set volatile baboon's colour to change when it is triggered to explode

### ISSUE THREAD

**Issue by evilgenious448** [LlemonDuck/tombs-of-amascut#89]
Hi @LlemonDuck and @rdutta,
I am unable to replicate the behavior in this gif from the following PR that allows for the Volatile Baboon's colour to change when it's fuze has been triggered so it explodes:
https://github.com/LlemonDuck/tombs-of-amascut/pull/84

I use the following settings:

- I have the baboon outline off since I was using better NPC highlight before you made this update and can't be bothered to migrate those settings to the TOA plugin atm.
- Volatile Baboon is set to be yellow with the tile radius of it's trigger and explosive range showing. 

![image](https://github.com/LlemonDuck/tombs-of-amascut/assets/32331499/4dc9bfcf-00dd-425d-a0c6-6cabadaddfce)

The outcome of these settings is that the baboon is always yellow, even when exploding. I would like it to turn red when triggered, just like in the gif. 

Thanks :)

**Comment by evilgenious448** [comment]
I just looked and saw it was removed in one of the commits. Would it be possible to add it back with the option to set it for those who want to use the feature?
It would be great to know when it's time to run away.

**Comment by rdutta** [comment]
Reason for its removal is in a collapsed comment:

> Remove this feature. Jagex has been lenient on not counting some stuff in the other puzzle rooms since they aren't combat, but I feel this oversteps.

**Comment by evilgenious448** [comment]
Fair enough, thank you!
