### ISSUE TITLE
Volatile Baboons Outline Not Showing

### ISSUE THREAD

**Issue by rnemer27** [LlemonDuck/tombs-of-amascut#91]
Volatile Boboons are not highlighting via the outline setting. It works when i use better npc highlight.

**Comment by LlemonDuck** [comment]
It may not be entirely clear from the config order, but it is intentional since the volatile baboons are a radius marker, and not tied to the other config options. They are controlled by the "Volatile Baboon Tile" option.

I'll reorder the config options to make it more clear.
