### ISSUE TITLE
[Feature Request] Hide players on last phase warden

### ISSUE THREAD

**Issue by Austin-ihasamoose** [LlemonDuck/tombs-of-amascut#94]
Hello, thanks for the awesome plugin!

My feature request would be a click to enable/disable setting to hide all other players on final phase warden so you can see the tiles the boulders are going on etc. Or instead of hide highlight outline of player, or perhaps a room select for hiding players as warden p2 can also be tricky to see where all the rocks are being thrown.

Thank you!

**Comment by LlemonDuck** [comment]
I've discussed this a bit in #58, but since this isn't a very ToA-specific problem, and also pretty niche toward high level raiders, I'd prefer to see someone implement this as a separate (global) plugin.
