### ISSUE TITLE
het suboptimal solve

### ISSUE THREAD

**Issue by emiljensen2** [LlemonDuck/tombs-of-amascut#95]
https://clips.twitch.tv/BoringPunchyAnteaterUnSane-9iCY47iOU1qPbkfs
The 2 west mirrors should be 1 tile more east

**Comment by LlemonDuck** [comment]
I'm not particularly interested in chasing down optimal solves for the mirror puzzle, it's just intended to give correct answers for casual raiders. Same goes for Kephri pathing.

It can be confusing to the majority of non-speedrunning raiders when things get too specific for that use case.

I'd also rather encourage good players to solve the puzzle without the plugin as it's intended, if they want to get better times.
